### ISSUE TITLE
Cannot import schedules

### ISSUE THREAD

**Issue by ProAviaAZ** [ProAviaAZ/phpvms_5.5.2.72#21]
Cannot import schedules.

No idea why yet. The following flights were in the CSV file (which I had exported using the export schedules function after adding them using add schedule). Below is result of import. None of the flights show in the schedules table though.

**FA270 was not added, reason: Data too long for column 'flighttype' at row 1

Imported FA7030 (KPHX to KONT)
FA7031 was not added, reason: Data too long for column 'flighttype' at row 1

FA720 was not added, reason: Data too long for column 'flighttype' at row 1

The import process is complete, added 4 schedules, updated 0, for a total of 1**

Received the following: Warning: unlink(C:\wamp64\www\phpvms_5.5.x-master\core\cacheschedules.csv): Resource temporarily unavailable in C:\wamp64\www\phpvms_5.5.x-master\admin\modules\Import\Import.php on line 482

**Comment by ProAviaAZ** [comment]
After adding
fclose($fp);
before line 482 - Warning fixed.....

Now get error that 'payforflight' in schedules table doesn't have a default value. Changed to 'As Defined:' and '0' allows it to continue.....

Then, get error that 'flighttype' in schedules table - data too long. So, changed 'Type' to 'varchar(2) and import is successful.

Need to check 'add schedule' in admin panel to see if it still works.

**Comment by ProAviaAZ** [comment]
'add schedule' seems to work with above changes to schedules table - but there MUST be data entered into each field (even if it is a '0') to add the schedule - except for Route and Notes.

**Comment by ProAviaAZ** [comment]
Do not close this until the issues with the schedules table in the DB have been addressed.

**Comment by ProAviaAZ** [comment]
After exporting schedules.csv from my live site, I was able to import that CSV file into the test site without issue.

I believe that has something to do with the CSV formatting. Using MS Excel messes up the CSV formatting. Use Open Office (freeware) instead.

**Comment by ProAviaAZ** [comment]
This now works.

Exported 'schedules.csv' from live site and imported successfully into development site. Previous issue may have been do to the way MS Excel handles CSV files. Using Open Office there is no issue

**Comment by jimbonh** [comment]
Another one to consider if you can find it, is Kingsoft Office 2013. Disengage the automatic upgrades by renaming the files, you'll see them. Also another one is LibreOffice, I find it to work for phpvms well. I'm using also as a test bed  IBM Lotus Symphony, its free now, and allows Internet side panels in the Program itself.
