### ISSUE TITLE
Install Routine update for php 7.2

### ISSUE THREAD

**Issue by ProAviaAZ** [ProAviaAZ/phpvms_5.5.2.72#38]
Install routine will not work in PHP 7.2

At present....
- Install phpVMS under PHP 5.6 and then change to PHP 7.2
- If PHP 5.6 not available on live site, install locally using Wamp/XAMPP and then export DB from Wamp/XAMPP and import to live environment. Then upload all files from local install to live environment. 
- If using local to live... change local.config.php after upload to live to reflect correct DBASE and SITE_URL parameters.

Future....
- Rewrite install routine to accommodate PHP 7.2
- Update DB install to MySQL 5.7

Going to need some help on updating install routine.

**Comment by ProAviaAZ** [comment]
Some progress has been made. Looking for feedback on the install using PHP 7.2
DB install for MySQL 5.7 has not been attempted yet. It does work under MySQL 5.6

**Comment by ProAviaAZ** [comment]
Install using PHP 7.2 should now work. There will be 3 Warnings on initial install - continue past them and it should install fine.

Still looking for a permanent solution.

**Comment by ProAviaAZ** [comment]
Install works under PHP 7.2

When initially going to install, 3 warnings will show. Continue past them. Additionally, after writing DB tables, another warning will show. Again, continue past it.

Attempting the fix I found online fixed the warnings from popping up, but lead to other issues with the install.

Will look for additional help with this issue.

**Warnings....**

**First 3 on initial install**

- PHP Warning:  Use of undefined constant DBASE_NAME - assumed 'DBASE_NAME' (this will throw an Error in a future version of PHP) in /xxxx/core/codon.config.php on line 90

- PHP Warning:  Use of undefined constant DBASE_SERVER - assumed 'DBASE_SERVER' (this will throw an Error in a future version of PHP) in /xxxx/core/codon.config.php on line 90

- PHP Warning:  Use of undefined constant DBASE_NAME - assumed 'DBASE_NAME' (this will throw an Error in a future version of PHP) in /xxxx/core/codon.config.php on line 90

**After writing to DB**

- PHP Warning:  Use of undefined constant TABLE_PREFIX - assumed 'TABLE_PREFIX' (this will throw an Error in a future version of PHP) in /xxxx/core/common/SettingsData.class.php on line 184

**Comment by ProAviaAZ** [comment]
**During the install ONLY** - if any of the above 'warning' messages show, ignore them. The install will complete successfully.

Some users reported not seeing these warnings during install. This may be due to the specific version of PHP installed or specific host settings.

**Comment by FroztIkon** [comment]
Might want to add in this as well:
`
PHP Version (5 required) | You need PHP 5 (your version: 7.2.24
-- | --
`
Edit:
install/includes/installer.class.php line 44 from:
`if($version[0] != '5')`
to
`if($version[0] != '7')`

**Comment by ProAviaAZ** [comment]
Can you explain this further? Are you seeing an issue during install?

phpVMS 5.5.2 - only installs under  PHP 5 (original simpilot version)
phpVMS 5.5.2.72 - only installs under PHP 7.0-7.2 (this version)

**Comment by FroztIkon** [comment]
Yes, using the released code from here (5.5.2.72), during the install process it checks php version.

**Comment by ProAviaAZ** [comment]
Yes, it is supposed to check the php version during install. 
phpVMS 5.5.2.72 requires use of PHP 7 - and works with PHP 7.0 - 7.2 . It does not work correctly with PHP 7.3 or greater at this time. And it is set to NOT allow install in PHP 5.x

/install/includes/installer class.php in line 44 already refers to PHP 7. 

If you are using phpVMS 5.5.2, it requires PHP 5
If you are using phpVMS 5.5.2.72, it requires PHP 7 (7.0-7.2)

So I am still not clear on what you believe needs to be added. Can you explain in more detail?
