### ISSUE TITLE
count() - check each fix

### ISSUE THREAD

**Issue by ProAviaAZ** [ProAviaAZ/phpvms_5.5.2.72#40]
Check each fix of count()

Should be

if(is_array($foo) || $foo instanceof Countable) {
    if count($foo) {
         do something;
    }
}

Of course with correct indent

**Comment by ProAviaAZ** [comment]
I'm pretty sure I reviewed all of the files that I made this change in and corrected those that needed it.

**Comment by FatihKoz** [comment]
```php
if (is_countable($foo) && count($foo)) {
  do something;
}
```

Cleaner and shorter version of your fix ;)
