### ISSUE TITLE
Admin error all pilots page/save changes

### ISSUE THREAD

**Issue by Capttuhd** [ProAviaAZ/phpvms_5.5.2.72#48]
When I edit my self on the all pilots page I get this error code at the top of the page.

Warning: count(): Parameter must be an array or an object that implements Countable in /xxxx/admin/modules/PilotAdmin/PilotAdmin.php on line 135

Rick

**Comment by ProAviaAZ** [comment]
This should fix it
https://github.com/ProAviaAZ/phpvms_5.5.2.72/commit/93e6080e93cd45d74baa9d3ad80c068dedc0ad8a

**Comment by Capttuhd** [comment]
That did it
Would you like me to start a new Issue with the pilots group error
Rick

**Comment by ProAviaAZ** [comment]
Thanks - Yes, start a new issue
