### ISSUE TITLE
edit pilot groups

### ISSUE THREAD

**Issue by Capttuhd** [ProAviaAZ/phpvms_5.5.2.72#49]
when I click on edit when trying to edit a pilot group I get this
![error1 pic](https://user-images.githubusercontent.com/56708359/67137421-a7274f00-f1fa-11e9-8c7e-65e18e98eafd.jpg)

**Comment by ProAviaAZ** [comment]
So you are going to Pilots & Groups, Pilot Groups and then click Edit next to a group you previously added. And that is when the error pops up? Or when you attempt to save your changes?

Verify that you are using an admin account with full admin privileges. 

I am unable to duplicate this on my live site or my development site. Any further into you can provide may help. Is error logging on your site active and if so are there any errors in the error_log file? If error logging is off, turn it on and try this again.

**Comment by Capttuhd** [comment]
I'm the only admin,, it's the original admin account, and I can't edit it
I created an a group called Pilots, and when I click on the edit button it goes to that page

**Comment by Capttuhd** [comment]
maybe it's a php version error

**Comment by ProAviaAZ** [comment]
Maybe, maybe not. Let's discuss more via PM on the forums. Once we find a solution, we will post it here.

**Comment by Capttuhd** [comment]
ok

**Comment by ProAviaAZ** [comment]
Solved by a full un-install and reinstall from scratch.
