### ISSUE TITLE
Issue adding airports.

### ISSUE THREAD

**Issue by xusmcxjasonx** [ProAviaAZ/phpvms_5.5.2.72#52]
Adding airports gives an error.

**Comment by ProAviaAZ** [comment]
What version of PHP are you using?
What version of MySQL or MariaDB are you using?
Check with your hosting company and ask if Strict Mode is on or off.

**Comment by xusmcxjasonx** [comment]
PHP 7.2 
I was testing in XAMPP, I could try to put it up on the website and see if the issues remain.

**Comment by xusmcxjasonx** [comment]
MySQL was 5.7 I believe. Also I was using your APLOOK branch.

**Comment by ProAviaAZ** [comment]
There have been odd reports of this happening. I suggest trying in XAMPP with MySql 5.6 to see if it works in that version. It's possible that MySQL 5.7 defaults to Strict Mode ON - if so, set it to OFF.

**Comment by xusmcxjasonx** [comment]
Still same error after testing on the APLOOK branch.. I can add it thru mysql perfectly but not thru admin panel.

**Comment by ProAviaAZ** [comment]
Ah - don't use the APlook branch as it's presently not working. I have pulled that branch from view to avoid future confusion. Go to the forums and download the APlook. You will have to do that mod manually after you have 5.5.2.72 installed.
https://forum.phpvms.net/topic/27452-airport-lookup-updated-vacentral-api-for-airport-lookup-only/

**Comment by ProAviaAZ** [comment]
I am guessing you were able to successfully install phpVMS 5.5.2.72 and then add the APlookup from the phpVMS forums. I am going to close this issue.
