### ISSUE TITLE
Use of MariaDb 10.2 

### ISSUE THREAD

**Issue by ghost** [ProAviaAZ/phpvms_5.5.2.72#54]
Hey, are you currently working on the MariaDB 10.2+ version? Or do you know when this will be published?

Greetings

**Comment by ProAviaAZ** [comment]
Haven't started yet. Too many real world issues right now.
Many of the issues seem related to strict mode. See if your host will turn it off.
Post on phpVMS forums about issues you may be presently having and we will try to help you out.

**Comment by ghost** [comment]
Hey,
I found a solution to this problem.

Disadvantage, it can only be used for VAs who host their VA themselves on a server (regardless of whether it is a V server, root or dedicated server).

Due to the small but fine change, phpvms now also works with MariaDB 10.3

Regards

**Comment by ghost** [comment]
For Contact: vincent.bomers@airgoldberg.com

**Comment by ProAviaAZ** [comment]
I would like to further discuss your proposed fix for Maria 10.2 and 10.3 . 
Please check your email.
