### ISSUE TITLE
IPv6 Compatibility (db column max length)

### ISSUE THREAD

**Issue by FatihKoz** [ProAviaAZ/phpvms_5.5.2.72#55]
Hi @ProAviaAZ ,

25 chars will not be enough to store v6 addresses. It should be at least 45 chars to avoid errors. 

So during install, setting ip related column length as `varchar(45)` may solve future issues with new members using ipv6. Also for current users of your release, running simple sql queries may help to solve this little problem.

`ALTER TABLE phpvms_pilots CHANGE lastip lastip VARCHAR(45)`

https://github.com/ProAviaAZ/phpvms_5.5.2.72/blob/master/install/sql/install.sql#L336

Same logic applies to the sessions table too;

https://github.com/ProAviaAZ/phpvms_5.5.2.72/blob/master/install/sql/install.sql#L471

`ALTER TABLE phpvms_sessions CHANGE ipaddress ipaddress VARCHAR(45)`

Safe flights

**Comment by ProAviaAZ** [comment]
Both lines updated from 25 to 45 character length.
Thanks!

**Comment by FatihKoz** [comment]
Great, hope it helps.
